// File auto-generated by protoc-gen-simple-ts
import * as match_strategy_pb from './match_strategy_pb'
import * as platform_v1_query_types from './match_strategy_types_sjs'
import * as platform_v1_query_mappers from './match_strategy_mappers_sjs'


export const mapMatchedStringValueToGrpcWeb = (input?: platform_v1_query_types.MatchedStringValue): match_strategy_pb.MatchedStringValue | undefined => {
	if (!input) return
	const result = new match_strategy_pb.MatchedStringValue()
	const tmpStrategy = mapMatchStrategyToGrpcWeb(input?.strategy);
    if (tmpStrategy !== undefined) result.setStrategy(tmpStrategy)
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapMatchedStringValueFromGrpcWeb = (input?: match_strategy_pb.MatchedStringValue): platform_v1_query_types.MatchedStringValue | undefined => {
	if (!input) return
	const result: platform_v1_query_types.MatchedStringValue = {
        strategy: mapMatchStrategyFromGrpcWeb(input.getStrategy()),
        value: input.getValue(),
	}
	return result
}

export const mapMatchStrategyToGrpcWeb = (input?: platform_v1_query_types.MatchStrategy): match_strategy_pb.MatchStrategy | undefined => {
	if (input === undefined) return
	switch (input) {
		case platform_v1_query_types.MatchStrategy.UNKNOWN_MATCH_STRATEGY: return match_strategy_pb.MatchStrategy.UNKNOWN_MATCH_STRATEGY
		case platform_v1_query_types.MatchStrategy.MATCH_EXACT: return match_strategy_pb.MatchStrategy.MATCH_EXACT
		case platform_v1_query_types.MatchStrategy.MATCH_EXACT_AND_NULL: return match_strategy_pb.MatchStrategy.MATCH_EXACT_AND_NULL
		case platform_v1_query_types.MatchStrategy.MATCH_NULL_ONLY: return match_strategy_pb.MatchStrategy.MATCH_NULL_ONLY
		case platform_v1_query_types.MatchStrategy.MATCH_ANY: return match_strategy_pb.MatchStrategy.MATCH_ANY
	}
}

export const mapMatchStrategyFromGrpcWeb = (input?: match_strategy_pb.MatchStrategy): platform_v1_query_types.MatchStrategy | undefined => {
	if (input === undefined) return
	switch (input) {
		case match_strategy_pb.MatchStrategy.UNKNOWN_MATCH_STRATEGY: return platform_v1_query_types.MatchStrategy.UNKNOWN_MATCH_STRATEGY
		case match_strategy_pb.MatchStrategy.MATCH_EXACT: return platform_v1_query_types.MatchStrategy.MATCH_EXACT
		case match_strategy_pb.MatchStrategy.MATCH_EXACT_AND_NULL: return platform_v1_query_types.MatchStrategy.MATCH_EXACT_AND_NULL
		case match_strategy_pb.MatchStrategy.MATCH_NULL_ONLY: return platform_v1_query_types.MatchStrategy.MATCH_NULL_ONLY
		case match_strategy_pb.MatchStrategy.MATCH_ANY: return platform_v1_query_types.MatchStrategy.MATCH_ANY
	}
}

