// File auto-generated by protoc-gen-simple-ts


export interface MatchedStringValue {
    strategy?: MatchStrategy,
    value?: string,
}


export enum MatchStrategy {
    UNKNOWN_MATCH_STRATEGY = 0,
    MATCH_EXACT = 1,
    MATCH_EXACT_AND_NULL = 2,
    MATCH_NULL_ONLY = 3,
    MATCH_ANY = 4,
}

