// File auto-generated by protoc-gen-simple-ts
import * as platform_v1_query_types from '../../platform/query/match_strategy_types_sjs'


export interface Resource {
    uid?: string,
    name?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    resource?: string,
    datasource?: Resource_Datasource,
    datasourceParamsCustom?: DatasourceParamsCustom,
    datasourceParamsElasticsearch?: DatasourceParamsElasticSearch,
    datasourceParamsGraphql?: DatasourceParamsGraphQL,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}


export enum Resource_Datasource {
    UNKNOWN_RESOURCE_TYPE = 0,
    ELASTICSEARCH = 1,
    GRAPHQL = 2,
    CUSTOM = 3,
}

export interface CustomDataSourceRequest {
    url?: string,
    method?: CustomDataSourceRequest_Method,
    body?: string,
    headers?: Array<string>,
}


export enum CustomDataSourceRequest_Method {
    UNKNOWN_CUSTOM_DATASOURCE_REQUEST_METHOD = 0,
    GET = 1,
    POST = 2,
    PUT = 3,
    PATCH = 4,
}

export interface DatasourceParamsCustom {
    datasource?: CustomDataSourceRequest,
}

export interface DatasourceParamsElasticSearch {
    index?: string,
}

export interface DatasourceParamsGraphQL {
    schema?: string,
    properties?: string,
    depth?: number,
    exclusions?: Array<string>,
}

export interface ViewOverride {
    uid?: string,
    userId?: string,
    domainId?: string,
    tenantId?: string,
    viewId?: string,
    data?: string,
    name?: string,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface List {
    uid?: string,
    name?: string,
    resourceId?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    columns?: Array<List_ColumnsEntry>,
    ordering?: Array<string>,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface List_ColumnsEntry {
    key?: string,
    value?: Column,
}

export interface Column {
    title?: string,
    template?: string,
}

export interface Filter {
    uid?: string,
    name?: string,
    resourceId?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    query?: string,
    sorting?: Array<string>,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface Page {
    uid?: string,
    name?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    viewIds?: Array<string>,
    slug?: string,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface View {
    uid?: string,
    name?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    template?: string,
    plugins?: Array<PluginInstance>,
    slug?: string,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface PluginInstance {
    uid?: string,
    dependsOn?: Array<string>,
    pluginId?: string,
    data?: string,
}

export interface Plugin {
    uid?: string,
    name?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    template?: string,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface GetListsRequest {
    resourceId?: platform_v1_query_types.MatchedStringValue,
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetListsResponse {
    lists?: Array<List>,
}

export interface GetResourcesRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    resource?: string,
    limit?: number,
    datasource?: Resource_Datasource,
    datasourceParamsCustom?: DatasourceParamsCustom,
    datasourceParamsElasticsearch?: DatasourceParamsElasticSearch,
    datasourceParamsGraphql?: DatasourceParamsGraphQL,
}

export interface GetResourcesResponse {
    resources?: Array<Resource>,
}

export interface GetFiltersRequest {
    resourceId?: platform_v1_query_types.MatchedStringValue,
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetFiltersResponse {
    filters?: Array<Filter>,
}

export interface GetPagesRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
    slug?: string,
}

export interface GetPagesResponse {
    pages?: Array<Page>,
}

export interface GetViewsRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetViewsResponse {
    views?: Array<View>,
}

export interface GetPluginsRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetPluginsResponse {
    plugins?: Array<Plugin>,
}

export interface GetViewOverridesRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    viewId?: string,
    limit?: number,
}

export interface GetViewOverridesResponse {
    viewOverrides?: Array<ViewOverride>,
}

