// File auto-generated by protoc-gen-simple-ts


export interface Action {
    uid?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    jobs?: Array<Job>,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}

export interface ActionResponse {
    uid?: string,
}

export interface ActionResult {
    uid?: string,
    jobs?: Array<Job>,
    summary?: JobsSummary,
}

export interface JobsSummary {
    total?: number,
    pending?: number,
    started?: number,
    completed?: number,
    failed?: number,
}

export interface JobRunRequirements {
    minTime?: string,
    jobsCompleted?: Array<string>,
}

export interface Job {
    uid?: string,
    userId?: string,
    tenantId?: string,
    domainId?: string,
    jobStatus?: JobStatus,
    jobType?: string,
    jobData?: string,
    runRequirements?: JobRunRequirements,
    order?: number,
    startedAt?: string,
    completedAt?: string,
    failedAt?: string,
    createdAt?: string,
    createdBy?: string,
    updatedAt?: string,
    updatedBy?: string,
    deletedAt?: string,
    deletedBy?: string,
}


export enum ActionType {
    UNKNOWN_ACTION_TYPE = 0,
    ACTION_TYPE_ONE_OFF = 1,
    ACTION_TYPE_SCHEDULED = 2,
}


export enum JobStatus {
    UNKNOWN_JOB_STATUS = 0,
    JOB_STATUS_PENDING = 1,
    JOB_STATUS_STARTED = 2,
    JOB_STATUS_COMPLETED = 3,
    JOB_STATUS_FAILED = 4,
}

