// source: src/action/crud/api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var src_ui_crud_api_pb = require('../../ui/crud/api_pb.js');
goog.object.extend(proto, src_ui_crud_api_pb);
goog.exportSymbol('proto.action.crud.v1.Action', null, global);
goog.exportSymbol('proto.action.crud.v1.ActionResponse', null, global);
goog.exportSymbol('proto.action.crud.v1.ActionResult', null, global);
goog.exportSymbol('proto.action.crud.v1.ActionType', null, global);
goog.exportSymbol('proto.action.crud.v1.Job', null, global);
goog.exportSymbol('proto.action.crud.v1.JobRunRequirements', null, global);
goog.exportSymbol('proto.action.crud.v1.JobStatus', null, global);
goog.exportSymbol('proto.action.crud.v1.JobsSummary', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.action.crud.v1.Action = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.action.crud.v1.Action.repeatedFields_, null);
};
goog.inherits(proto.action.crud.v1.Action, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.action.crud.v1.Action.displayName = 'proto.action.crud.v1.Action';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.action.crud.v1.ActionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.action.crud.v1.ActionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.action.crud.v1.ActionResponse.displayName = 'proto.action.crud.v1.ActionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.action.crud.v1.ActionResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.action.crud.v1.ActionResult.repeatedFields_, null);
};
goog.inherits(proto.action.crud.v1.ActionResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.action.crud.v1.ActionResult.displayName = 'proto.action.crud.v1.ActionResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.action.crud.v1.JobsSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.action.crud.v1.JobsSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.action.crud.v1.JobsSummary.displayName = 'proto.action.crud.v1.JobsSummary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.action.crud.v1.JobRunRequirements = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.action.crud.v1.JobRunRequirements.repeatedFields_, null);
};
goog.inherits(proto.action.crud.v1.JobRunRequirements, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.action.crud.v1.JobRunRequirements.displayName = 'proto.action.crud.v1.JobRunRequirements';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.action.crud.v1.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.action.crud.v1.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.action.crud.v1.Job.displayName = 'proto.action.crud.v1.Job';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.action.crud.v1.Action.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.action.crud.v1.Action.prototype.toObject = function(opt_includeInstance) {
  return proto.action.crud.v1.Action.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.action.crud.v1.Action} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.Action.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tenantid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    domainid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    jobsList: jspb.Message.toObjectList(msg.getJobsList(),
    proto.action.crud.v1.Job.toObject, includeInstance),
    createdat: jspb.Message.getFieldWithDefault(msg, 990, ""),
    createdby: jspb.Message.getFieldWithDefault(msg, 991, ""),
    updatedat: jspb.Message.getFieldWithDefault(msg, 992, ""),
    updatedby: jspb.Message.getFieldWithDefault(msg, 993, ""),
    deletedat: jspb.Message.getFieldWithDefault(msg, 994, ""),
    deletedby: jspb.Message.getFieldWithDefault(msg, 995, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.action.crud.v1.Action}
 */
proto.action.crud.v1.Action.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.action.crud.v1.Action;
  return proto.action.crud.v1.Action.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.action.crud.v1.Action} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.action.crud.v1.Action}
 */
proto.action.crud.v1.Action.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomainid(value);
      break;
    case 5:
      var value = new proto.action.crud.v1.Job;
      reader.readMessage(value,proto.action.crud.v1.Job.deserializeBinaryFromReader);
      msg.addJobs(value);
      break;
    case 990:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedat(value);
      break;
    case 991:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedby(value);
      break;
    case 992:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedat(value);
      break;
    case 993:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedby(value);
      break;
    case 994:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeletedat(value);
      break;
    case 995:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeletedby(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.action.crud.v1.Action.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.action.crud.v1.Action.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.action.crud.v1.Action} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.Action.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTenantid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDomainid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getJobsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.action.crud.v1.Job.serializeBinaryToWriter
    );
  }
  f = message.getCreatedat();
  if (f.length > 0) {
    writer.writeString(
      990,
      f
    );
  }
  f = message.getCreatedby();
  if (f.length > 0) {
    writer.writeString(
      991,
      f
    );
  }
  f = message.getUpdatedat();
  if (f.length > 0) {
    writer.writeString(
      992,
      f
    );
  }
  f = message.getUpdatedby();
  if (f.length > 0) {
    writer.writeString(
      993,
      f
    );
  }
  f = message.getDeletedat();
  if (f.length > 0) {
    writer.writeString(
      994,
      f
    );
  }
  f = message.getDeletedby();
  if (f.length > 0) {
    writer.writeString(
      995,
      f
    );
  }
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string userId = 2;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tenantId = 3;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getTenantid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setTenantid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string domainId = 4;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getDomainid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setDomainid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated Job jobs = 5;
 * @return {!Array<!proto.action.crud.v1.Job>}
 */
proto.action.crud.v1.Action.prototype.getJobsList = function() {
  return /** @type{!Array<!proto.action.crud.v1.Job>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.action.crud.v1.Job, 5));
};


/**
 * @param {!Array<!proto.action.crud.v1.Job>} value
 * @return {!proto.action.crud.v1.Action} returns this
*/
proto.action.crud.v1.Action.prototype.setJobsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.action.crud.v1.Job=} opt_value
 * @param {number=} opt_index
 * @return {!proto.action.crud.v1.Job}
 */
proto.action.crud.v1.Action.prototype.addJobs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.action.crud.v1.Job, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.clearJobsList = function() {
  return this.setJobsList([]);
};


/**
 * optional string createdAt = 990;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getCreatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 990, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 990, value);
};


/**
 * optional string createdBy = 991;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getCreatedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 991, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setCreatedby = function(value) {
  return jspb.Message.setProto3StringField(this, 991, value);
};


/**
 * optional string updatedAt = 992;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getUpdatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 992, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 992, value);
};


/**
 * optional string updatedBy = 993;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getUpdatedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 993, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setUpdatedby = function(value) {
  return jspb.Message.setProto3StringField(this, 993, value);
};


/**
 * optional string deletedAt = 994;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getDeletedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 994, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setDeletedat = function(value) {
  return jspb.Message.setProto3StringField(this, 994, value);
};


/**
 * optional string deletedBy = 995;
 * @return {string}
 */
proto.action.crud.v1.Action.prototype.getDeletedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 995, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Action} returns this
 */
proto.action.crud.v1.Action.prototype.setDeletedby = function(value) {
  return jspb.Message.setProto3StringField(this, 995, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.action.crud.v1.ActionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.action.crud.v1.ActionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.action.crud.v1.ActionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.ActionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.action.crud.v1.ActionResponse}
 */
proto.action.crud.v1.ActionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.action.crud.v1.ActionResponse;
  return proto.action.crud.v1.ActionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.action.crud.v1.ActionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.action.crud.v1.ActionResponse}
 */
proto.action.crud.v1.ActionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.action.crud.v1.ActionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.action.crud.v1.ActionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.action.crud.v1.ActionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.ActionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.action.crud.v1.ActionResponse.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.ActionResponse} returns this
 */
proto.action.crud.v1.ActionResponse.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.action.crud.v1.ActionResult.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.action.crud.v1.ActionResult.prototype.toObject = function(opt_includeInstance) {
  return proto.action.crud.v1.ActionResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.action.crud.v1.ActionResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.ActionResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    jobsList: jspb.Message.toObjectList(msg.getJobsList(),
    proto.action.crud.v1.Job.toObject, includeInstance),
    summary: (f = msg.getSummary()) && proto.action.crud.v1.JobsSummary.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.action.crud.v1.ActionResult}
 */
proto.action.crud.v1.ActionResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.action.crud.v1.ActionResult;
  return proto.action.crud.v1.ActionResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.action.crud.v1.ActionResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.action.crud.v1.ActionResult}
 */
proto.action.crud.v1.ActionResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 2:
      var value = new proto.action.crud.v1.Job;
      reader.readMessage(value,proto.action.crud.v1.Job.deserializeBinaryFromReader);
      msg.addJobs(value);
      break;
    case 3:
      var value = new proto.action.crud.v1.JobsSummary;
      reader.readMessage(value,proto.action.crud.v1.JobsSummary.deserializeBinaryFromReader);
      msg.setSummary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.action.crud.v1.ActionResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.action.crud.v1.ActionResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.action.crud.v1.ActionResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.ActionResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJobsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.action.crud.v1.Job.serializeBinaryToWriter
    );
  }
  f = message.getSummary();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.action.crud.v1.JobsSummary.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.action.crud.v1.ActionResult.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.ActionResult} returns this
 */
proto.action.crud.v1.ActionResult.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Job jobs = 2;
 * @return {!Array<!proto.action.crud.v1.Job>}
 */
proto.action.crud.v1.ActionResult.prototype.getJobsList = function() {
  return /** @type{!Array<!proto.action.crud.v1.Job>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.action.crud.v1.Job, 2));
};


/**
 * @param {!Array<!proto.action.crud.v1.Job>} value
 * @return {!proto.action.crud.v1.ActionResult} returns this
*/
proto.action.crud.v1.ActionResult.prototype.setJobsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.action.crud.v1.Job=} opt_value
 * @param {number=} opt_index
 * @return {!proto.action.crud.v1.Job}
 */
proto.action.crud.v1.ActionResult.prototype.addJobs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.action.crud.v1.Job, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.action.crud.v1.ActionResult} returns this
 */
proto.action.crud.v1.ActionResult.prototype.clearJobsList = function() {
  return this.setJobsList([]);
};


/**
 * optional JobsSummary summary = 3;
 * @return {?proto.action.crud.v1.JobsSummary}
 */
proto.action.crud.v1.ActionResult.prototype.getSummary = function() {
  return /** @type{?proto.action.crud.v1.JobsSummary} */ (
    jspb.Message.getWrapperField(this, proto.action.crud.v1.JobsSummary, 3));
};


/**
 * @param {?proto.action.crud.v1.JobsSummary|undefined} value
 * @return {!proto.action.crud.v1.ActionResult} returns this
*/
proto.action.crud.v1.ActionResult.prototype.setSummary = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.action.crud.v1.ActionResult} returns this
 */
proto.action.crud.v1.ActionResult.prototype.clearSummary = function() {
  return this.setSummary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.action.crud.v1.ActionResult.prototype.hasSummary = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.action.crud.v1.JobsSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.action.crud.v1.JobsSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.action.crud.v1.JobsSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.JobsSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
    total: jspb.Message.getFieldWithDefault(msg, 1, 0),
    pending: jspb.Message.getFieldWithDefault(msg, 2, 0),
    started: jspb.Message.getFieldWithDefault(msg, 3, 0),
    completed: jspb.Message.getFieldWithDefault(msg, 4, 0),
    failed: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.action.crud.v1.JobsSummary}
 */
proto.action.crud.v1.JobsSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.action.crud.v1.JobsSummary;
  return proto.action.crud.v1.JobsSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.action.crud.v1.JobsSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.action.crud.v1.JobsSummary}
 */
proto.action.crud.v1.JobsSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotal(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPending(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStarted(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCompleted(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFailed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.action.crud.v1.JobsSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.action.crud.v1.JobsSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.action.crud.v1.JobsSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.JobsSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPending();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getStarted();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getCompleted();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getFailed();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional int32 total = 1;
 * @return {number}
 */
proto.action.crud.v1.JobsSummary.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.action.crud.v1.JobsSummary} returns this
 */
proto.action.crud.v1.JobsSummary.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 pending = 2;
 * @return {number}
 */
proto.action.crud.v1.JobsSummary.prototype.getPending = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.action.crud.v1.JobsSummary} returns this
 */
proto.action.crud.v1.JobsSummary.prototype.setPending = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 started = 3;
 * @return {number}
 */
proto.action.crud.v1.JobsSummary.prototype.getStarted = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.action.crud.v1.JobsSummary} returns this
 */
proto.action.crud.v1.JobsSummary.prototype.setStarted = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 completed = 4;
 * @return {number}
 */
proto.action.crud.v1.JobsSummary.prototype.getCompleted = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.action.crud.v1.JobsSummary} returns this
 */
proto.action.crud.v1.JobsSummary.prototype.setCompleted = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 failed = 5;
 * @return {number}
 */
proto.action.crud.v1.JobsSummary.prototype.getFailed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.action.crud.v1.JobsSummary} returns this
 */
proto.action.crud.v1.JobsSummary.prototype.setFailed = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.action.crud.v1.JobRunRequirements.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.action.crud.v1.JobRunRequirements.prototype.toObject = function(opt_includeInstance) {
  return proto.action.crud.v1.JobRunRequirements.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.action.crud.v1.JobRunRequirements} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.JobRunRequirements.toObject = function(includeInstance, msg) {
  var f, obj = {
    mintime: jspb.Message.getFieldWithDefault(msg, 1, ""),
    jobscompletedList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.action.crud.v1.JobRunRequirements}
 */
proto.action.crud.v1.JobRunRequirements.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.action.crud.v1.JobRunRequirements;
  return proto.action.crud.v1.JobRunRequirements.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.action.crud.v1.JobRunRequirements} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.action.crud.v1.JobRunRequirements}
 */
proto.action.crud.v1.JobRunRequirements.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMintime(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addJobscompleted(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.action.crud.v1.JobRunRequirements.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.action.crud.v1.JobRunRequirements.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.action.crud.v1.JobRunRequirements} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.JobRunRequirements.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMintime();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJobscompletedList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string minTime = 1;
 * @return {string}
 */
proto.action.crud.v1.JobRunRequirements.prototype.getMintime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.JobRunRequirements} returns this
 */
proto.action.crud.v1.JobRunRequirements.prototype.setMintime = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string jobsCompleted = 2;
 * @return {!Array<string>}
 */
proto.action.crud.v1.JobRunRequirements.prototype.getJobscompletedList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.action.crud.v1.JobRunRequirements} returns this
 */
proto.action.crud.v1.JobRunRequirements.prototype.setJobscompletedList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.action.crud.v1.JobRunRequirements} returns this
 */
proto.action.crud.v1.JobRunRequirements.prototype.addJobscompleted = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.action.crud.v1.JobRunRequirements} returns this
 */
proto.action.crud.v1.JobRunRequirements.prototype.clearJobscompletedList = function() {
  return this.setJobscompletedList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.action.crud.v1.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.action.crud.v1.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.action.crud.v1.Job} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tenantid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    domainid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    jobstatus: jspb.Message.getFieldWithDefault(msg, 5, 0),
    jobtype: jspb.Message.getFieldWithDefault(msg, 6, ""),
    jobdata: jspb.Message.getFieldWithDefault(msg, 7, ""),
    runrequirements: (f = msg.getRunrequirements()) && proto.action.crud.v1.JobRunRequirements.toObject(includeInstance, f),
    order: jspb.Message.getFieldWithDefault(msg, 9, 0),
    startedat: jspb.Message.getFieldWithDefault(msg, 100, ""),
    completedat: jspb.Message.getFieldWithDefault(msg, 101, ""),
    failedat: jspb.Message.getFieldWithDefault(msg, 102, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 990, ""),
    createdby: jspb.Message.getFieldWithDefault(msg, 991, ""),
    updatedat: jspb.Message.getFieldWithDefault(msg, 992, ""),
    updatedby: jspb.Message.getFieldWithDefault(msg, 993, ""),
    deletedat: jspb.Message.getFieldWithDefault(msg, 994, ""),
    deletedby: jspb.Message.getFieldWithDefault(msg, 995, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.action.crud.v1.Job}
 */
proto.action.crud.v1.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.action.crud.v1.Job;
  return proto.action.crud.v1.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.action.crud.v1.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.action.crud.v1.Job}
 */
proto.action.crud.v1.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomainid(value);
      break;
    case 5:
      var value = /** @type {!proto.action.crud.v1.JobStatus} */ (reader.readEnum());
      msg.setJobstatus(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobtype(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobdata(value);
      break;
    case 8:
      var value = new proto.action.crud.v1.JobRunRequirements;
      reader.readMessage(value,proto.action.crud.v1.JobRunRequirements.deserializeBinaryFromReader);
      msg.setRunrequirements(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOrder(value);
      break;
    case 100:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartedat(value);
      break;
    case 101:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompletedat(value);
      break;
    case 102:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailedat(value);
      break;
    case 990:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedat(value);
      break;
    case 991:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedby(value);
      break;
    case 992:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedat(value);
      break;
    case 993:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedby(value);
      break;
    case 994:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeletedat(value);
      break;
    case 995:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeletedby(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.action.crud.v1.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.action.crud.v1.Job.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.action.crud.v1.Job} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.action.crud.v1.Job.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTenantid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDomainid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getJobstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getJobtype();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getJobdata();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getRunrequirements();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.action.crud.v1.JobRunRequirements.serializeBinaryToWriter
    );
  }
  f = message.getOrder();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getStartedat();
  if (f.length > 0) {
    writer.writeString(
      100,
      f
    );
  }
  f = message.getCompletedat();
  if (f.length > 0) {
    writer.writeString(
      101,
      f
    );
  }
  f = message.getFailedat();
  if (f.length > 0) {
    writer.writeString(
      102,
      f
    );
  }
  f = message.getCreatedat();
  if (f.length > 0) {
    writer.writeString(
      990,
      f
    );
  }
  f = message.getCreatedby();
  if (f.length > 0) {
    writer.writeString(
      991,
      f
    );
  }
  f = message.getUpdatedat();
  if (f.length > 0) {
    writer.writeString(
      992,
      f
    );
  }
  f = message.getUpdatedby();
  if (f.length > 0) {
    writer.writeString(
      993,
      f
    );
  }
  f = message.getDeletedat();
  if (f.length > 0) {
    writer.writeString(
      994,
      f
    );
  }
  f = message.getDeletedby();
  if (f.length > 0) {
    writer.writeString(
      995,
      f
    );
  }
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string userId = 2;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tenantId = 3;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getTenantid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setTenantid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string domainId = 4;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getDomainid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setDomainid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional JobStatus jobStatus = 5;
 * @return {!proto.action.crud.v1.JobStatus}
 */
proto.action.crud.v1.Job.prototype.getJobstatus = function() {
  return /** @type {!proto.action.crud.v1.JobStatus} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.action.crud.v1.JobStatus} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setJobstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string jobType = 6;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getJobtype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setJobtype = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string jobData = 7;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getJobdata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setJobdata = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional JobRunRequirements runRequirements = 8;
 * @return {?proto.action.crud.v1.JobRunRequirements}
 */
proto.action.crud.v1.Job.prototype.getRunrequirements = function() {
  return /** @type{?proto.action.crud.v1.JobRunRequirements} */ (
    jspb.Message.getWrapperField(this, proto.action.crud.v1.JobRunRequirements, 8));
};


/**
 * @param {?proto.action.crud.v1.JobRunRequirements|undefined} value
 * @return {!proto.action.crud.v1.Job} returns this
*/
proto.action.crud.v1.Job.prototype.setRunrequirements = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.clearRunrequirements = function() {
  return this.setRunrequirements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.action.crud.v1.Job.prototype.hasRunrequirements = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int32 order = 9;
 * @return {number}
 */
proto.action.crud.v1.Job.prototype.getOrder = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setOrder = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string startedAt = 100;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getStartedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 100, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setStartedat = function(value) {
  return jspb.Message.setProto3StringField(this, 100, value);
};


/**
 * optional string completedAt = 101;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getCompletedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 101, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setCompletedat = function(value) {
  return jspb.Message.setProto3StringField(this, 101, value);
};


/**
 * optional string failedAt = 102;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getFailedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 102, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setFailedat = function(value) {
  return jspb.Message.setProto3StringField(this, 102, value);
};


/**
 * optional string createdAt = 990;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getCreatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 990, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 990, value);
};


/**
 * optional string createdBy = 991;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getCreatedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 991, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setCreatedby = function(value) {
  return jspb.Message.setProto3StringField(this, 991, value);
};


/**
 * optional string updatedAt = 992;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getUpdatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 992, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 992, value);
};


/**
 * optional string updatedBy = 993;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getUpdatedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 993, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setUpdatedby = function(value) {
  return jspb.Message.setProto3StringField(this, 993, value);
};


/**
 * optional string deletedAt = 994;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getDeletedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 994, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setDeletedat = function(value) {
  return jspb.Message.setProto3StringField(this, 994, value);
};


/**
 * optional string deletedBy = 995;
 * @return {string}
 */
proto.action.crud.v1.Job.prototype.getDeletedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 995, ""));
};


/**
 * @param {string} value
 * @return {!proto.action.crud.v1.Job} returns this
 */
proto.action.crud.v1.Job.prototype.setDeletedby = function(value) {
  return jspb.Message.setProto3StringField(this, 995, value);
};


/**
 * @enum {number}
 */
proto.action.crud.v1.ActionType = {
  UNKNOWN_ACTION_TYPE: 0,
  ACTION_TYPE_ONE_OFF: 1,
  ACTION_TYPE_SCHEDULED: 2
};

/**
 * @enum {number}
 */
proto.action.crud.v1.JobStatus = {
  UNKNOWN_JOB_STATUS: 0,
  JOB_STATUS_PENDING: 1,
  JOB_STATUS_STARTED: 2,
  JOB_STATUS_COMPLETED: 3,
  JOB_STATUS_FAILED: 4
};

goog.object.extend(exports, proto.action.crud.v1);
