// File auto-generated by protoc-gen-simple-ts
import * as api_pb from './api_pb'
import * as action_api_v1_types from './api_types_sjs'
import * as action_api_v1_mappers from './api_mappers_sjs'
import * as action_crud_v1_types from '../crud/api_types_sjs'
import * as action_crud_v1_mappers from '../crud/api_mappers_sjs'


export const mapGetJobRequestToGrpcWeb = (input?: action_api_v1_types.GetJobRequest): api_pb.GetJobRequest | undefined => {
	if (!input) return
	const result = new api_pb.GetJobRequest()
	if (input?.uid !== undefined) result.setUid(input.uid)
	return result
}

export const mapGetJobRequestFromGrpcWeb = (input?: api_pb.GetJobRequest): action_api_v1_types.GetJobRequest | undefined => {
	if (!input) return
	const result: action_api_v1_types.GetJobRequest = {
        uid: input.getUid(),
	}
	return result
}

export const mapGetJobResponseToGrpcWeb = (input?: action_api_v1_types.GetJobResponse): api_pb.GetJobResponse | undefined => {
	if (!input) return
	const result = new api_pb.GetJobResponse()
	const tmpJob = action_crud_v1_mappers.mapJobToGrpcWeb(input?.job);
    if (tmpJob !== undefined) result.setJob(tmpJob)
	return result
}

export const mapGetJobResponseFromGrpcWeb = (input?: api_pb.GetJobResponse): action_api_v1_types.GetJobResponse | undefined => {
	if (!input) return
	const result: action_api_v1_types.GetJobResponse = {
        job: action_crud_v1_mappers.mapJobFromGrpcWeb(input.getJob()),
	}
	return result
}

export const mapInitiateActionRequestToGrpcWeb = (input?: action_api_v1_types.InitiateActionRequest): api_pb.InitiateActionRequest | undefined => {
	if (!input) return
	const result = new api_pb.InitiateActionRequest()
	if (input?.actionId !== undefined) result.setActionid(input.actionId)
	if (input?.resourceId !== undefined) result.setResourceid(input.resourceId)
	if (input?.filter !== undefined) result.setFilter(input.filter)
	if (input?.actionData !== undefined) result.setActiondata(input.actionData)
	return result
}

export const mapInitiateActionRequestFromGrpcWeb = (input?: api_pb.InitiateActionRequest): action_api_v1_types.InitiateActionRequest | undefined => {
	if (!input) return
	const result: action_api_v1_types.InitiateActionRequest = {
        actionId: input.getActionid(),
        resourceId: input.getResourceid(),
        filter: input.getFilter(),
        actionData: input.getActiondata(),
	}
	return result
}

export const mapInitiateActionResponseToGrpcWeb = (input?: action_api_v1_types.InitiateActionResponse): api_pb.InitiateActionResponse | undefined => {
	if (!input) return
	const result = new api_pb.InitiateActionResponse()
	const tmpJob = action_crud_v1_mappers.mapJobToGrpcWeb(input?.job);
    if (tmpJob !== undefined) result.setJob(tmpJob)
	return result
}

export const mapInitiateActionResponseFromGrpcWeb = (input?: api_pb.InitiateActionResponse): action_api_v1_types.InitiateActionResponse | undefined => {
	if (!input) return
	const result: action_api_v1_types.InitiateActionResponse = {
        job: action_crud_v1_mappers.mapJobFromGrpcWeb(input.getJob()),
	}
	return result
}

