// File auto-generated by protoc-gen-simple-ts
import * as action_crud_v1_types from '../crud/api_types_sjs'


export interface GetJobRequest {
    uid?: string,
}

export interface GetJobResponse {
    job?: action_crud_v1_types.Job,
}

export interface InitiateActionRequest {
    actionId?: string,
    resourceId?: string,
    filter?: string,
    actionData?: string,
}

export interface InitiateActionResponse {
    job?: action_crud_v1_types.Job,
}

