// File auto-generated by protoc-gen-simple-js


export type FileDescriptorSet = {
    file: Array<google_protobuf.FileDescriptorProto>,
}

export type FileDescriptorProto = {
    name: string,
    package: string,
    dependency: Array<string>,
    public_dependency: Array<number>,
    weak_dependency: Array<number>,
    message_type: Array<google_protobuf.DescriptorProto>,
    enum_type: Array<google_protobuf.EnumDescriptorProto>,
    service: Array<google_protobuf.ServiceDescriptorProto>,
    extension: Array<google_protobuf.FieldDescriptorProto>,
    options: google_protobuf.FileOptions,
    source_code_info: google_protobuf.SourceCodeInfo,
    syntax: string,
}

export type DescriptorProto = {
    name: string,
    field: Array<google_protobuf.FieldDescriptorProto>,
    extension: Array<google_protobuf.FieldDescriptorProto>,
    nested_type: Array<google_protobuf.DescriptorProto>,
    enum_type: Array<google_protobuf.EnumDescriptorProto>,
    extension_range: Array<google_protobuf.ExtensionRange>,
    oneof_decl: Array<google_protobuf.OneofDescriptorProto>,
    options: google_protobuf.MessageOptions,
    reserved_range: Array<google_protobuf.ReservedRange>,
    reserved_name: Array<string>,
}

export type ExtensionRangeOptions = {
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type FieldDescriptorProto = {
    name: string,
    number: number,
    label: google_protobuf.Label,
    type: google_protobuf.Type,
    type_name: string,
    extendee: string,
    default_value: string,
    oneof_index: number,
    json_name: string,
    options: google_protobuf.FieldOptions,
    proto3_optional: boolean,
}

export type OneofDescriptorProto = {
    name: string,
    options: google_protobuf.OneofOptions,
}

export type EnumDescriptorProto = {
    name: string,
    value: Array<google_protobuf.EnumValueDescriptorProto>,
    options: google_protobuf.EnumOptions,
    reserved_range: Array<google_protobuf.EnumReservedRange>,
    reserved_name: Array<string>,
}

export type EnumValueDescriptorProto = {
    name: string,
    number: number,
    options: google_protobuf.EnumValueOptions,
}

export type ServiceDescriptorProto = {
    name: string,
    method: Array<google_protobuf.MethodDescriptorProto>,
    options: google_protobuf.ServiceOptions,
}

export type MethodDescriptorProto = {
    name: string,
    input_type: string,
    output_type: string,
    options: google_protobuf.MethodOptions,
    client_streaming: boolean,
    server_streaming: boolean,
}

export type FileOptions = {
    java_package: string,
    java_outer_classname: string,
    java_multiple_files: boolean,
    java_generate_equals_and_hash: boolean,
    java_string_check_utf8: boolean,
    optimize_for: google_protobuf.OptimizeMode,
    go_package: string,
    cc_generic_services: boolean,
    java_generic_services: boolean,
    py_generic_services: boolean,
    php_generic_services: boolean,
    deprecated: boolean,
    cc_enable_arenas: boolean,
    objc_class_prefix: string,
    csharp_namespace: string,
    swift_prefix: string,
    php_class_prefix: string,
    php_namespace: string,
    php_metadata_namespace: string,
    ruby_package: string,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type MessageOptions = {
    message_set_wire_format: boolean,
    no_standard_descriptor_accessor: boolean,
    deprecated: boolean,
    map_entry: boolean,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type FieldOptions = {
    ctype: google_protobuf.CType,
    packed: boolean,
    jstype: google_protobuf.JSType,
    lazy: boolean,
    deprecated: boolean,
    weak: boolean,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type OneofOptions = {
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type EnumOptions = {
    allow_alias: boolean,
    deprecated: boolean,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type EnumValueOptions = {
    deprecated: boolean,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type ServiceOptions = {
    deprecated: boolean,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type MethodOptions = {
    deprecated: boolean,
    idempotency_level: google_protobuf.IdempotencyLevel,
    uninterpreted_option: Array<google_protobuf.UninterpretedOption>,
}

export type UninterpretedOption = {
    name: Array<google_protobuf.NamePart>,
    identifier_value: string,
    positive_int_value: number,
    negative_int_value: number,
    double_value: number,
    string_value: bytes,
    aggregate_value: string,
}

export type SourceCodeInfo = {
    location: Array<google_protobuf.Location>,
}

export type GeneratedCodeInfo = {
    annotation: Array<google_protobuf.Annotation>,
}

