// File auto-generated by protoc-gen-simple-ts


export interface FileDescriptorSet {
    file?: Array<FileDescriptorProto>,
}

export interface FileDescriptorProto {
    name?: string,
    package?: string,
    dependency?: Array<string>,
    public_dependency?: Array<number>,
    weak_dependency?: Array<number>,
    message_type?: Array<DescriptorProto>,
    enum_type?: Array<EnumDescriptorProto>,
    service?: Array<ServiceDescriptorProto>,
    extension?: Array<FieldDescriptorProto>,
    options?: FileOptions,
    source_code_info?: SourceCodeInfo,
    syntax?: string,
}

export interface DescriptorProto {
    name?: string,
    field?: Array<FieldDescriptorProto>,
    extension?: Array<FieldDescriptorProto>,
    nested_type?: Array<DescriptorProto>,
    enum_type?: Array<EnumDescriptorProto>,
    extension_range?: Array<DescriptorProto_ExtensionRange>,
    oneof_decl?: Array<OneofDescriptorProto>,
    options?: MessageOptions,
    reserved_range?: Array<DescriptorProto_ReservedRange>,
    reserved_name?: Array<string>,
}

export interface DescriptorProto_ExtensionRange {
    start?: number,
    end?: number,
    options?: ExtensionRangeOptions,
}

export interface DescriptorProto_ReservedRange {
    start?: number,
    end?: number,
}

export interface ExtensionRangeOptions {
    uninterpreted_option?: Array<UninterpretedOption>,
}

export interface FieldDescriptorProto {
    name?: string,
    number?: number,
    label?: FieldDescriptorProto_Label,
    type?: FieldDescriptorProto_Type,
    type_name?: string,
    extendee?: string,
    default_value?: string,
    oneof_index?: number,
    json_name?: string,
    options?: FieldOptions,
    proto3_optional?: boolean,
}


export enum FieldDescriptorProto_Type {
    TYPE_DOUBLE = 1,
    TYPE_FLOAT = 2,
    TYPE_INT64 = 3,
    TYPE_UINT64 = 4,
    TYPE_INT32 = 5,
    TYPE_FIXED64 = 6,
    TYPE_FIXED32 = 7,
    TYPE_BOOL = 8,
    TYPE_STRING = 9,
    TYPE_GROUP = 10,
    TYPE_MESSAGE = 11,
    TYPE_BYTES = 12,
    TYPE_UINT32 = 13,
    TYPE_ENUM = 14,
    TYPE_SFIXED32 = 15,
    TYPE_SFIXED64 = 16,
    TYPE_SINT32 = 17,
    TYPE_SINT64 = 18,
}


export enum FieldDescriptorProto_Label {
    LABEL_OPTIONAL = 1,
    LABEL_REQUIRED = 2,
    LABEL_REPEATED = 3,
}

export interface OneofDescriptorProto {
    name?: string,
    options?: OneofOptions,
}

export interface EnumDescriptorProto {
    name?: string,
    value?: Array<EnumValueDescriptorProto>,
    options?: EnumOptions,
    reserved_range?: Array<EnumDescriptorProto_EnumReservedRange>,
    reserved_name?: Array<string>,
}

export interface EnumDescriptorProto_EnumReservedRange {
    start?: number,
    end?: number,
}

export interface EnumValueDescriptorProto {
    name?: string,
    number?: number,
    options?: EnumValueOptions,
}

export interface ServiceDescriptorProto {
    name?: string,
    method?: Array<MethodDescriptorProto>,
    options?: ServiceOptions,
}

export interface MethodDescriptorProto {
    name?: string,
    input_type?: string,
    output_type?: string,
    options?: MethodOptions,
    client_streaming?: boolean,
    server_streaming?: boolean,
}

export interface FileOptions {
    java_package?: string,
    java_outer_classname?: string,
    java_multiple_files?: boolean,
    java_generate_equals_and_hash?: boolean,
    java_string_check_utf8?: boolean,
    optimize_for?: FileOptions_OptimizeMode,
    go_package?: string,
    cc_generic_services?: boolean,
    java_generic_services?: boolean,
    py_generic_services?: boolean,
    php_generic_services?: boolean,
    deprecated?: boolean,
    cc_enable_arenas?: boolean,
    objc_class_prefix?: string,
    csharp_namespace?: string,
    swift_prefix?: string,
    php_class_prefix?: string,
    php_namespace?: string,
    php_metadata_namespace?: string,
    ruby_package?: string,
    uninterpreted_option?: Array<UninterpretedOption>,
}


export enum FileOptions_OptimizeMode {
    SPEED = 1,
    CODE_SIZE = 2,
    LITE_RUNTIME = 3,
}

export interface MessageOptions {
    message_set_wire_format?: boolean,
    no_standard_descriptor_accessor?: boolean,
    deprecated?: boolean,
    map_entry?: boolean,
    uninterpreted_option?: Array<UninterpretedOption>,
}

export interface FieldOptions {
    ctype?: FieldOptions_CType,
    packed?: boolean,
    jstype?: FieldOptions_JSType,
    lazy?: boolean,
    deprecated?: boolean,
    weak?: boolean,
    uninterpreted_option?: Array<UninterpretedOption>,
}


export enum FieldOptions_CType {
    STRING = 0,
    CORD = 1,
    STRING_PIECE = 2,
}


export enum FieldOptions_JSType {
    JS_NORMAL = 0,
    JS_STRING = 1,
    JS_NUMBER = 2,
}

export interface OneofOptions {
    uninterpreted_option?: Array<UninterpretedOption>,
}

export interface EnumOptions {
    allow_alias?: boolean,
    deprecated?: boolean,
    uninterpreted_option?: Array<UninterpretedOption>,
}

export interface EnumValueOptions {
    deprecated?: boolean,
    uninterpreted_option?: Array<UninterpretedOption>,
}

export interface ServiceOptions {
    deprecated?: boolean,
    uninterpreted_option?: Array<UninterpretedOption>,
}

export interface MethodOptions {
    deprecated?: boolean,
    idempotency_level?: MethodOptions_IdempotencyLevel,
    uninterpreted_option?: Array<UninterpretedOption>,
}


export enum MethodOptions_IdempotencyLevel {
    IDEMPOTENCY_UNKNOWN = 0,
    NO_SIDE_EFFECTS = 1,
    IDEMPOTENT = 2,
}

export interface UninterpretedOption {
    name?: Array<UninterpretedOption_NamePart>,
    identifier_value?: string,
    positive_int_value?: number,
    negative_int_value?: number,
    double_value?: number,
    string_value?: bytes,
    aggregate_value?: string,
}

export interface UninterpretedOption_NamePart {
    name_part?: string,
    is_extension?: boolean,
}

export interface SourceCodeInfo {
    location?: Array<SourceCodeInfo_Location>,
}

export interface SourceCodeInfo_Location {
    path?: Array<number>,
    span?: Array<number>,
    leading_comments?: string,
    trailing_comments?: string,
    leading_detached_comments?: Array<string>,
}

export interface GeneratedCodeInfo {
    annotation?: Array<GeneratedCodeInfo_Annotation>,
}

export interface GeneratedCodeInfo_Annotation {
    path?: Array<number>,
    source_file?: string,
    begin?: number,
    end?: number,
}

