// File auto-generated by protoc-gen-simple-ts
import * as wrappers_pb from './wrappers_pb'
import * as google_protobuf_types from './wrappers_types_sjs'
import * as google_protobuf_mappers from './wrappers_mappers_sjs'


export const mapDoubleValueToGrpcWeb = (input?: google_protobuf_types.DoubleValue): wrappers_pb.DoubleValue | undefined => {
	if (!input) return
	const result = new wrappers_pb.DoubleValue()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapDoubleValueFromGrpcWeb = (input?: wrappers_pb.DoubleValue): google_protobuf_types.DoubleValue | undefined => {
	if (!input) return
	const result: google_protobuf_types.DoubleValue = {
        value: input.getValue(),
	}
	return result
}

export const mapFloatValueToGrpcWeb = (input?: google_protobuf_types.FloatValue): wrappers_pb.FloatValue | undefined => {
	if (!input) return
	const result = new wrappers_pb.FloatValue()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapFloatValueFromGrpcWeb = (input?: wrappers_pb.FloatValue): google_protobuf_types.FloatValue | undefined => {
	if (!input) return
	const result: google_protobuf_types.FloatValue = {
        value: input.getValue(),
	}
	return result
}

export const mapInt64ValueToGrpcWeb = (input?: google_protobuf_types.Int64Value): wrappers_pb.Int64Value | undefined => {
	if (!input) return
	const result = new wrappers_pb.Int64Value()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapInt64ValueFromGrpcWeb = (input?: wrappers_pb.Int64Value): google_protobuf_types.Int64Value | undefined => {
	if (!input) return
	const result: google_protobuf_types.Int64Value = {
        value: input.getValue(),
	}
	return result
}

export const mapUInt64ValueToGrpcWeb = (input?: google_protobuf_types.UInt64Value): wrappers_pb.UInt64Value | undefined => {
	if (!input) return
	const result = new wrappers_pb.UInt64Value()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapUInt64ValueFromGrpcWeb = (input?: wrappers_pb.UInt64Value): google_protobuf_types.UInt64Value | undefined => {
	if (!input) return
	const result: google_protobuf_types.UInt64Value = {
        value: input.getValue(),
	}
	return result
}

export const mapInt32ValueToGrpcWeb = (input?: google_protobuf_types.Int32Value): wrappers_pb.Int32Value | undefined => {
	if (!input) return
	const result = new wrappers_pb.Int32Value()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapInt32ValueFromGrpcWeb = (input?: wrappers_pb.Int32Value): google_protobuf_types.Int32Value | undefined => {
	if (!input) return
	const result: google_protobuf_types.Int32Value = {
        value: input.getValue(),
	}
	return result
}

export const mapUInt32ValueToGrpcWeb = (input?: google_protobuf_types.UInt32Value): wrappers_pb.UInt32Value | undefined => {
	if (!input) return
	const result = new wrappers_pb.UInt32Value()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapUInt32ValueFromGrpcWeb = (input?: wrappers_pb.UInt32Value): google_protobuf_types.UInt32Value | undefined => {
	if (!input) return
	const result: google_protobuf_types.UInt32Value = {
        value: input.getValue(),
	}
	return result
}

export const mapBoolValueToGrpcWeb = (input?: google_protobuf_types.BoolValue): wrappers_pb.BoolValue | undefined => {
	if (!input) return
	const result = new wrappers_pb.BoolValue()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapBoolValueFromGrpcWeb = (input?: wrappers_pb.BoolValue): google_protobuf_types.BoolValue | undefined => {
	if (!input) return
	const result: google_protobuf_types.BoolValue = {
        value: input.getValue(),
	}
	return result
}

export const mapStringValueToGrpcWeb = (input?: google_protobuf_types.StringValue): wrappers_pb.StringValue | undefined => {
	if (!input) return
	const result = new wrappers_pb.StringValue()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapStringValueFromGrpcWeb = (input?: wrappers_pb.StringValue): google_protobuf_types.StringValue | undefined => {
	if (!input) return
	const result: google_protobuf_types.StringValue = {
        value: input.getValue(),
	}
	return result
}

export const mapBytesValueToGrpcWeb = (input?: google_protobuf_types.BytesValue): wrappers_pb.BytesValue | undefined => {
	if (!input) return
	const result = new wrappers_pb.BytesValue()
	if (input?.value !== undefined) result.setValue(input.value)
	return result
}

export const mapBytesValueFromGrpcWeb = (input?: wrappers_pb.BytesValue): google_protobuf_types.BytesValue | undefined => {
	if (!input) return
	const result: google_protobuf_types.BytesValue = {
        value: input.getValue(),
	}
	return result
}

