// File auto-generated by protoc-gen-simple-js
import * as ui_crud_v1 from '../crud/api_sjs'
import * as platform_v1_query from '../../platform/query/match_strategy_sjs'


export type NewResourceRequest = {
    resource: ui_crud_v1.Resource,
}

export type GetResourceRequest = {
    uid: string,
}

export type PutResourceRequest = {
    resource: ui_crud_v1.Resource,
}

export type DelResourceRequest = {
    uid: string,
}

export type GetResourcesRequest = {
    userId: platform_v1_query.MatchedStringValue,
    tenantId: platform_v1_query.MatchedStringValue,
    domainId: platform_v1_query.MatchedStringValue,
    resource: string,
    limit: number,
}

export type GetResourcesResponse = {
    resources: Array<ui_crud_v1.Resource>,
}

export type NewListRequest = {
    list: ui_crud_v1.List,
}

export type GetListRequest = {
    uid: string,
}

export type PutListRequest = {
    list: ui_crud_v1.List,
}

export type DelListRequest = {
    uid: string,
}

export type GetListsRequest = {
    resourceId: platform_v1_query.MatchedStringValue,
    userId: platform_v1_query.MatchedStringValue,
    tenantId: platform_v1_query.MatchedStringValue,
    domainId: platform_v1_query.MatchedStringValue,
    limit: number,
}

export type GetListsResponse = {
    lists: Array<ui_crud_v1.List>,
}

export type NewFilterRequest = {
    filter: ui_crud_v1.Filter,
}

export type GetFilterRequest = {
    uid: string,
}

export type PutFilterRequest = {
    filter: ui_crud_v1.Filter,
}

export type DelFilterRequest = {
    uid: string,
}

export type GetFiltersRequest = {
    resourceId: platform_v1_query.MatchedStringValue,
    userId: platform_v1_query.MatchedStringValue,
    tenantId: platform_v1_query.MatchedStringValue,
    domainId: platform_v1_query.MatchedStringValue,
    limit: number,
}

export type GetFiltersResponse = {
    filters: Array<ui_crud_v1.Filter>,
}

export type NewPageRequest = {
    page: ui_crud_v1.Page,
}

export type GetPageRequest = {
    uid: string,
}

export type PutPageRequest = {
    page: ui_crud_v1.Page,
}

export type DelPageRequest = {
    uid: string,
}

export type GetPagesRequest = {
    userId: platform_v1_query.MatchedStringValue,
    tenantId: platform_v1_query.MatchedStringValue,
    domainId: platform_v1_query.MatchedStringValue,
    limit: number,
}

export type GetPagesResponse = {
    pages: Array<ui_crud_v1.Page>,
}

export type NewViewRequest = {
    view: ui_crud_v1.View,
}

export type GetViewRequest = {
    uid: string,
}

export type PutViewRequest = {
    view: ui_crud_v1.View,
}

export type DelViewRequest = {
    uid: string,
}

export type GetViewsRequest = {
    userId: platform_v1_query.MatchedStringValue,
    tenantId: platform_v1_query.MatchedStringValue,
    domainId: platform_v1_query.MatchedStringValue,
    limit: number,
}

export type GetViewsResponse = {
    views: Array<ui_crud_v1.View>,
}

export type NewPluginRequest = {
    plugin: ui_crud_v1.Plugin,
}

export type GetPluginRequest = {
    uid: string,
}

export type PutPluginRequest = {
    plugin: ui_crud_v1.Plugin,
}

export type DelPluginRequest = {
    uid: string,
}

export type GetPluginsRequest = {
    userId: platform_v1_query.MatchedStringValue,
    tenantId: platform_v1_query.MatchedStringValue,
    domainId: platform_v1_query.MatchedStringValue,
    limit: number,
}

export type GetPluginsResponse = {
    plugins: Array<ui_crud_v1.Plugin>,
}

export type GetUIRequest = {
    userId: string,
    tenantId: string,
    domainId: string,
    limit: number,
    resourceId: string,
    resource: string,
    lists: boolean,
    filters: boolean,
}

export type GetUIResponse = {
    resource: ui_crud_v1.Resource,
    resources: Array<ui_crud_v1.Resource>,
    lists: Array<ui_crud_v1.List>,
    filters: Array<ui_crud_v1.Filter>,
}

