// File auto-generated by protoc-gen-simple-ts
import * as ui_crud_v1_types from '../crud/api_types_sjs'
import * as platform_v1_query_types from '../../platform/query/match_strategy_types_sjs'


export interface NewResourceRequest {
    resource?: ui_crud_v1_types.Resource,
}

export interface GetResourceRequest {
    uid?: string,
}

export interface PutResourceRequest {
    resource?: ui_crud_v1_types.Resource,
}

export interface DelResourceRequest {
    uid?: string,
}

export interface GetResourcesRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    resource?: string,
    limit?: number,
    datasource?: ui_crud_v1_types.Resource_Datasource,
    datasourceParamsCustom?: ui_crud_v1_types.DatasourceParamsCustom,
    datasourceParamsElasticsearch?: ui_crud_v1_types.DatasourceParamsElasticSearch,
    datasourceParamsGraphql?: ui_crud_v1_types.DatasourceParamsGraphQL,
}

export interface GetResourcesResponse {
    resources?: Array<ui_crud_v1_types.Resource>,
}

export interface NewListRequest {
    list?: ui_crud_v1_types.List,
}

export interface GetListRequest {
    uid?: string,
}

export interface PutListRequest {
    list?: ui_crud_v1_types.List,
}

export interface DelListRequest {
    uid?: string,
}

export interface GetListsRequest {
    resourceId?: platform_v1_query_types.MatchedStringValue,
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetListsResponse {
    lists?: Array<ui_crud_v1_types.List>,
}

export interface NewFilterRequest {
    filter?: ui_crud_v1_types.Filter,
}

export interface GetFilterRequest {
    uid?: string,
}

export interface PutFilterRequest {
    filter?: ui_crud_v1_types.Filter,
}

export interface DelFilterRequest {
    uid?: string,
}

export interface GetFiltersRequest {
    resourceId?: platform_v1_query_types.MatchedStringValue,
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetFiltersResponse {
    filters?: Array<ui_crud_v1_types.Filter>,
}

export interface NewPageRequest {
    page?: ui_crud_v1_types.Page,
}

export interface GetPageRequest {
    uid?: string,
}

export interface PutPageRequest {
    page?: ui_crud_v1_types.Page,
}

export interface DelPageRequest {
    uid?: string,
}

export interface GetPagesRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
    slug?: string,
}

export interface GetPagesResponse {
    pages?: Array<ui_crud_v1_types.Page>,
}

export interface NewViewRequest {
    view?: ui_crud_v1_types.View,
}

export interface GetViewRequest {
    uid?: string,
}

export interface PutViewRequest {
    view?: ui_crud_v1_types.View,
}

export interface DelViewRequest {
    uid?: string,
}

export interface GetViewsRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetViewsResponse {
    views?: Array<ui_crud_v1_types.View>,
}

export interface NewPluginRequest {
    plugin?: ui_crud_v1_types.Plugin,
}

export interface GetPluginRequest {
    uid?: string,
}

export interface PutPluginRequest {
    plugin?: ui_crud_v1_types.Plugin,
}

export interface DelPluginRequest {
    uid?: string,
}

export interface GetPluginsRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    limit?: number,
}

export interface GetPluginsResponse {
    plugins?: Array<ui_crud_v1_types.Plugin>,
}

export interface GetUIRequest {
    userId?: string,
    tenantId?: string,
    domainId?: string,
    slug?: string,
    viewId?: string,
}

export interface GetUIResponse {
    page?: ui_crud_v1_types.Page,
    views?: Array<GetUIResponse_ViewsEntry>,
    plugins?: Array<GetUIResponse_PluginsEntry>,
    viewOverridesByView?: Array<GetUIResponse_ViewOverridesByViewEntry>,
}

export interface GetUIResponse_ViewsEntry {
    key?: string,
    value?: ui_crud_v1_types.View,
}

export interface GetUIResponse_PluginsEntry {
    key?: string,
    value?: ui_crud_v1_types.Plugin,
}

export interface GetUIResponse_ViewOverridesByViewEntry {
    key?: string,
    value?: RepeatedViewOverride,
}

export interface RepeatedViewOverride {
    viewOverrides?: Array<ui_crud_v1_types.ViewOverride>,
}

export interface InitiateSchemaSyncRequest {
    change?: SchemaChangeType,
    schema?: string,
    tenantId?: string,
}

export interface InitiateSchemaSyncResponse {
    resourceId?: string,
    listId?: string,
    filterId?: string,
    pageId?: string,
    viewId?: string,
}

export interface NewViewOverrideRequest {
    viewOverride?: ui_crud_v1_types.ViewOverride,
}

export interface GetViewOverrideRequest {
    uid?: string,
}

export interface PutViewOverrideRequest {
    viewOverride?: ui_crud_v1_types.ViewOverride,
}

export interface DelViewOverrideRequest {
    uid?: string,
}

export interface GetViewOverridesRequest {
    userId?: platform_v1_query_types.MatchedStringValue,
    tenantId?: platform_v1_query_types.MatchedStringValue,
    domainId?: platform_v1_query_types.MatchedStringValue,
    viewId?: string,
    limit?: number,
}

export interface GetViewOverridesResponse {
    viewOverrides?: Array<ui_crud_v1_types.ViewOverride>,
}


export enum SchemaChangeType {
    UNKNOWN_SCHEMA_CHANGE_TYPE = 0,
    UPSERT = 1,
    DELETE = 2,
}

