// File auto-generated by protoc-gen-simple-ts


export interface GetObjectsRequest {
    resourceId?: string,
    query?: string,
    limit?: number,
    sorting?: Array<string>,
    cursor?: string,
}

export interface GetObjectsResponse {
    results?: string,
    total?: number,
    cursor?: string,
}

export interface GetSchemaRequest {
    resourceId?: string,
}

export interface GetFieldSchemaRequest {
    resourceId?: string,
    accessor?: string,
}

export interface GetSchemaResponse {
    schema?: SchemaField,
}

export interface SchemaField {
    name?: string,
    type?: string,
    fields?: Array<SchemaField>,
    metadata?: SchemaFieldMetadata,
    accessor?: string,
}

export interface SchemaFieldMetadata {
    mapping?: string,
    type?: string,
    values?: Array<SchemaFieldMetadataValue>,
    label?: string,
}

export interface SchemaFieldMetadataValue {
    label?: string,
    value?: string,
    active?: boolean,
    defaultValue?: boolean,
}

