// File auto-generated by protoc-gen-simple-js


export type GetObjectsRequest = {
    resourceId: string,
    query: string,
    limit: number,
    sorting: Array<string>,
    cursor: string,
}

export type GetObjectsResponse = {
    results: string,
    total: number,
    cursor: string,
}

export type GetSchemaRequest = {
    resourceId: string,
}

export type GetFieldSchemaRequest = {
    resourceId: string,
    accessor: string,
}

export type GetSchemaResponse = {
    schema: query_api_v1.SchemaField,
}

export type SchemaField = {
    name: string,
    type: string,
    fields: Array<query_api_v1.SchemaField>,
    metadata: query_api_v1.SchemaFieldMetadata,
    accessor: string,
}

export type SchemaFieldMetadata = {
    mapping: string,
    type: string,
    values: Array<query_api_v1.SchemaFieldMetadataValue>,
}

export type SchemaFieldMetadataValue = {
    label: string,
    value: string,
    active: boolean,
    defaultValue: boolean,
}

