// File auto-generated by protoc-gen-simple-js


export type Http = {
    rules: Array<google_api.HttpRule>,
    fully_decode_reserved_expansion: boolean,
}

export type HttpRule = {
    selector: string,
    get: string,
    put: string,
    post: string,
    delete: string,
    patch: string,
    custom: google_api.CustomHttpPattern,
    body: string,
    response_body: string,
    additional_bindings: Array<google_api.HttpRule>,
}

export type CustomHttpPattern = {
    kind: string,
    path: string,
}

