// File auto-generated by protoc-gen-simple-ts
import * as action_crud_v1_types from '../crud/api_types_sjs'


export interface Event {
    version?: number,
    type?: EventType,
    data?: string,
}

export interface ExecuteJobData {
    job?: action_crud_v1_types.Job,
    actionId?: string,
}

export interface JobStatusChangeData {
    oldJob?: action_crud_v1_types.Job,
    newJob?: action_crud_v1_types.Job,
    actionId?: string,
}


export enum EventType {
    UNKNOWN_EVENT_TYPE = 0,
    EXECUTE_JOB = 1,
    JOB_STATUS_CHANGE = 2,
}

